apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2023-10-25T06-33-25Z
          command:
            - /bin/bash
            - -c
          args:
            - minio server /storage --console-address :9001
          env:
            # Minio access key and secret key
            - name: MINIO_ROOT_USER
              value: "minioadmin"
            - name: MINIO_ROOT_PASSWORD
              value: "minioadmin"
          ports:
            - containerPort: 9000
            - containerPort: 9001
          volumeMounts:
            - name: minio-pv # must match the volume name, below
              mountPath: "/storage"
      volumes:
        - name: minio-pv
          persistentVolumeClaim:
            claimName: minio-pvc
---
apiVersion: batch/v1
kind: Job
metadata:
  name: minio-init
spec:
  template:
    spec:
      containers:
        - name: minio-client
          image: minio/mc:RELEASE.2023-10-24T21-42-22Z
          env:
            - name: MC_HOST_minio
              value: "http://minioadmin:minioadmin@minio-svc:9000"
          command: ["/bin/sh"]
          args:
            - -c
            - >-
              /usr/bin/mc rm -r --force minio/loki;
              /usr/bin/mc mb minio/loki;
              /usr/bin/mc anonymous set public minio/loki;
              /usr/bin/mc rm -r --force minio/tempo;
              /usr/bin/mc mb minio/tempo;
              /usr/bin/mc anonymous set public minio/tempo;
              exit 0;
      restartPolicy: OnFailure