kind: Service
apiVersion: v1
metadata:
  name: minio-svc
  namespace: monitoring
spec:
  selector:
    app: minio
  ports:
    - name: api
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: console
      protocol: TCP
      port: 9001
      targetPort: 9001
  type: NodePort