version: "3.9"

services:
  event-store:
    image: quarkus-cqrs/event-store:1.0.0-SNAPSHOT
    environment:
      - QUARKUS_HTTP_PORT=9020
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=postgres
      - KAFKA_BOOTSTRAP_SERVERS=BROKER://kafka:9092
      - QUARKUS_DATASOURCE_DB_KIND=postgresql
      - QUARKUS_DATASOURCE_REACTIVE_URL=vertx-reactive:postgresql://postgres:5432/microservices
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/microservices
      - QUARKUS_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://tempo:4317
      - QUARKUS_LOG_HANDLER_GELF_ENABLED=true
      - QUARKUS_LOG_HANDLER_GELF_HOST=logstash
      - QUARKUS_LOG_HANDLER_GELF_PORT=12201
      - QUARKUS_LOG_HANDLER_GELF_INCLUDE_FULL_MDC=false
      - QUARKUS_LOG_HANDLER_GELF_ADDITIONAL_FIELD__ENV__VALUE=docker
    ports:
      - "9020:9020"
    networks:
      - cqrs
    deploy:
      resources:
        limits:
          memory: 300m
          cpus: '10.0'

  view-store:
    image: quarkus-cqrs/view-store:1.0.0-SNAPSHOT
    environment:
      - QUARKUS_HTTP_PORT=9010
      - KAFKA_BOOTSTRAP_SERVERS=BROKER://kafka:9092
      - QUARKUS_MONGODB_CONNECTION_STRING=mongodb://mongodb:27017
      - QUARKUS_MONGODB_DATABASE=microservices
      - QUARKUS_MONGODB_CREDENTIALS_USERNAME=admin
      - QUARKUS_MONGODB_CREDENTIALS_PASSWORD=admin
      - QUARKUS_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://tempo:4317
      - QUARKUS_LOG_HANDLER_GELF_ENABLED=true
      - QUARKUS_LOG_HANDLER_GELF_HOST=logstash
      - QUARKUS_LOG_HANDLER_GELF_PORT=12201
      - QUARKUS_LOG_HANDLER_GELF_INCLUDE_FULL_MDC=false
      - QUARKUS_LOG_HANDLER_GELF_ADDITIONAL_FIELD__ENV__VALUE=docker
    ports:
      - "9010:9010"
    networks:
      - cqrs
    deploy:
      resources:
        limits:
          memory: 300m
          cpus: '10.0'

networks:
  cqrs:
    driver: bridge