version: "3.9"

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-remote-write-receiver'
      - '--enable-feature=exemplar-storage'
    volumes:
      - prometheus_data:/prometheus
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - cqrs

  tempo:
    image: grafana/tempo
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
      - ./monitoring/tempo/tempo.yml:/etc/tempo.yml
      - tempo_data:/tmp/tempo
    ports:
      - "3200:3200"  # tempo
      - "4317:4317"  # otlp grpc
    networks:
      - cqrs
    depends_on:
      - prometheus

  loki:
    image: grafana/loki
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki
    ports:
      - "3100:3100"
    networks:
      - cqrs

  logstash:
    image: grafana/logstash-output-loki
    environment:
      - LS_JAVA_OPTS=-Xmx3g # Increase heap size
    volumes:
      - ./monitoring/logstash/gelf.conf:/usr/share/logstash/pipeline/gelf.conf:ro
    ports:
      - "12201:12201/udp"
      - "5000:5000"
      - "9600:9600"
    networks:
      - cqrs
    depends_on:
      - loki

  grafana:
    restart: always
    image: grafana/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=tempoSearch traceqlEditor traceToMetrics
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./monitoring/grafana/provisioning/dashboards/:/etc/grafana/provisioning/dashboards/
    ports:
      - '3005:3000'
    networks:
      - cqrs
    depends_on:
      - prometheus
      - tempo
      - loki

volumes:
  grafana_data:
  prometheus_data:
  tempo_data:
  loki_data:

networks:
  cqrs:
    driver: bridge