version: "3.9"

services:
  postgres:
    image: postgres:14.2
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - cqrs
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=microservices
      - POSTGRES_HOST=5432
    command: -p 5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  mongodb:
    image: docker.io/bitnami/mongodb:4.4
    environment:
      BITNAMI_DEBUG: "false"
      ALLOW_EMPTY_PASSWORD: "yes"
      MONGODB_SYSTEM_LOG_VERBOSITY: "0"
      MONGODB_DISABLE_SYSTEM_LOG: "no"
      MONGODB_DISABLE_JAVASCRIPT: "no"
      MONGODB_ENABLE_JOURNAL: "yes"
      MONGODB_ENABLE_IPV6: "no"
      MONGODB_ENABLE_DIRECTORY_PER_DB: "no"
      MONGODB_DATABASE: "microservices"
      MONGODB_USERNAME: "admin"
      MONGODB_PASSWORD: "admin"
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - cqrs

  kafka:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9092:9092"
      - "9094:9094"
    networks:
      - cqrs
    volumes:
      - kafka_data:/bitnami
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true

  kafka-init:
    image: docker.io/bitnami/kafka:3.4
    networks:
      - cqrs
    depends_on:
      - kafka
    entrypoint: >
      /bin/sh -c "
      /opt/bitnami/kafka/bin/kafka-topics.sh \
      --bootstrap-server=BROKER://kafka:9092 \ 
      --topic event-store \
      --partitions=3 \
      --create
      exit 0;
      "

volumes:
  pg_data:
  kafka_data:
  mongodb_data:

networks:
  cqrs:
    driver: bridge
