version: "3.9"

services:
  prometheus:
    image: prom/prometheus:v2.47.2
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-remote-write-receiver'
      - '--enable-feature=exemplar-storage'
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - cqrs

  tempo:
    image: grafana/tempo:2.2.4
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
      - ./tempo/tempo.yml:/etc/tempo.yml
      - tempo_data:/tmp/tempo
    ports:
      - "3200:3200"  # tempo
      - "4317:4317"  # otlp grpc
    networks:
      - cqrs
    depends_on:
      - prometheus

  loki:
    image: grafana/loki:2.8.6
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/loki.yaml:/etc/loki/local-config.yaml:ro
      - loki_data:/loki
    ports:
      - "3100:3100"
    networks:
      - cqrs

  logstash:
    image: grafana/logstash-output-loki:2.8.6-amd64
    environment:
      - LS_JAVA_OPTS=-Xmx3g # Increase heap size
    volumes:
      - ./logstash/gelf.conf:/usr/share/logstash/pipeline/gelf.conf:ro
    ports:
      - "12201:12201/udp"
      - "5000:5000"
      - "9600:9600"
    networks:
      - cqrs
    depends_on:
      - loki

  minio:
    image: minio/minio:RELEASE.2023-10-25T06-33-25Z
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - cqrs
    command: server ~ --address ':9000' --console-address ':9001'

  minio-init:
    image: minio/mc
    networks:
      - cqrs
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc rm -r --force myminio/loki;
      /usr/bin/mc mb myminio/loki;
      /usr/bin/mc policy set public myminio/loki;
      exit 0;
      "

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.1
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - "9101:8080"
    networks:
      - cqrs

  grafana:
    restart: always
    image: grafana/grafana:9.5.3
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=tempoSearch traceqlEditor traceToMetrics
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./grafana/provisioning/dashboards/:/etc/grafana/provisioning/dashboards/
    ports:
      - '3005:3000'
    networks:
      - cqrs
    depends_on:
      - prometheus
      - tempo
      - loki
      - cadvisor

volumes:
  grafana_data:
  prometheus_data:
  tempo_data:
  loki_data:

networks:
  cqrs:
    driver: bridge