#  docker compose -f docker-compose-jenkins.yml up -d --build --force-recreate
services:
  jenkins:
    build: jenkins/controller
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home:rw
      - ./jenkins/casc.d:/var/jenkins_home/casc.d/:ro
      # Mounting the ssh private key as "container secret" makes it available in JCasc as the variable ${SSH_AGENT_KEY}
      - ./jenkins/secrets/id_jenkins.pem:/run/secrets/SSH_AGENT_KEY:ro
    environment:
      - JENKINS_EXT_URL=http://localhost:8080
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc.d/
      - PUBLIC_IP
    networks:
      - cqrs
  jenkins-agent-1:
    platform: linux/amd64
    build: jenkins/agent
    restart: unless-stopped
    privileged: true
    volumes:
      - jenkins-agent1-data:/home/jenkins:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBpNqXQ4x7fPPUBbYPxKF77Zqq6d35iPCD2chg644OUD noone@localhost.local
    networks:
      - cqrs
  jenkins-agent-2:
    platform: linux/amd64
    build: jenkins/agent
    restart: unless-stopped
    privileged: true
    volumes:
      - jenkins-agent2-data:/home/jenkins:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBpNqXQ4x7fPPUBbYPxKF77Zqq6d35iPCD2chg644OUD noone@localhost.local
    networks:
      - cqrs
  jenkins-agent-3:
    platform: linux/amd64
    build: jenkins/agent
    restart: unless-stopped
    privileged: true
    volumes:
      - jenkins-agent3-data:/home/jenkins:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBpNqXQ4x7fPPUBbYPxKF77Zqq6d35iPCD2chg644OUD noone@localhost.local
    networks:
      - cqrs
volumes:
  jenkins-data:
  jenkins-agent1-data:
  jenkins-agent2-data:
  jenkins-agent3-data:
networks:
  cqrs:
    driver: bridge