apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: load-test
spec:
  configurationAsCode:
    configurations: []
    secret:
      name: ""
  groovyScripts:
    configurations: []
    secret:
      name: ""
  jenkinsAPISettings:
    authorizationStrategy: createUser
  master:
    basePlugins:
      - name: kubernetes
        version: "4151.v6fa_f0fb_0b_4c9"
      - name: workflow-job
        version: "1385.vb_58b_86ea_fff1"
      - name: workflow-aggregator
        version: "596.v8c21c963d92d"
      - name: git
        version: "5.2.1"
      - name: job-dsl
        version: "1.87"
      - name: configuration-as-code
        version: "1763.vb_fe9c1b_83f7b"
      - name: kubernetes-credentials-provider
        version: "1.258.v95949f923a_a_e"
      - name: gatling
        version: "1.3.0"
      - name: parameter-separator
        version: "129.v86b_98b_cb_5274"
    disableCSRFProtection: false
    containers:
      - name: jenkins-master
        image: jenkins/jenkins:2.437-jdk17
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 12
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 100
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 80
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 1500m
            memory: 3Gi
          requests:
            cpu: "1"
            memory: 500Mi
  seedJobAgentImage: jenkins/inbound-agent:latest-alpine-jdk17
  seedJobs:
    - id: jenkins-operator
      targets: "kubernetes/jenkins/cicd/jobs/*.jenkins"
      description: "Load test pipeline"
      repositoryBranch: jenkins
      repositoryUrl: http://code.webnodes.co.uk/geek/quarkus-cqrs.git