global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:

  - job_name: 'cadvisor'
    static_configs:
      - targets: [ "cadvisor:8080" ]

  - job_name: 'event-store'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: [ 'host.docker.internal:9020' ]

  - job_name: 'view-store'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: [ 'host.docker.internal:9010' ]
