apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  datasources.yml: |
    apiVersion: 1

    # list of datasources that should be deleted from the database
    deleteDatasources:
      - name: Prometheus
        orgId: 1
      - name: Tempo
        orgId: 1
      - name: Loki
        orgId: 1

    datasources:
      - name: Prometheus
        type: prometheus
        uid: e4e0224e-c538-4ae6-9468-dbcdb40209c0
        access: proxy
        orgId: 1
        url: http://prometheus-svc.monitoring.svc.cluster.local:9090
        basicAuth: false
        isDefault: true
        version: 1
        editable: true
        jsonData:
          httpMethod: POST
          defaultEditor: code
          prometheusType: Prometheus
          prometheusVersion: 2.40.1
      - name: Tempo
        type: tempo
        uid: 337b05fb-0159-4229-b9ce-ca151182522f
        access: proxy
        orgId: 1
        url: http://tempo-svc.monitoring.svc.cluster.local:3200
        basicAuth: false
        isDefault: false
        editable: true
        jsonData:
          traceQuery:
            timeShiftEnabled: false
            spanEndTimeShift: ""
            spanStartTimeShift: ""
          tracesToMetrics:
            datasourceUid: e4e0224e-c538-4ae6-9468-dbcdb40209c0
            queries:
              - name: Rate
                query: sum(rate(http_server_requests_seconds_count{$$__tags}[$$__rate_interval]))
              - name: Duration (Sum)
                query: sum(rate(http_server_requests_seconds_sum{$$__tags, status!~"5.."}[$$__rate_interval]))/sum(rate(http_server_requests_seconds_count{$$__tags,
                  status!~"5.."}[$$__rate_interval]))
              - name: Duration (Max)
                query: max(http_server_requests_seconds_max{$$__tags, status!~"5.."})
            spanEndTimeShift: "+1h"
            spanStartTimeShift: "-1h"
            tags:
              - key: service.name
                value: kubernetes_name
          tracesToLogsV2:
            customQuery: true
            datasourceUid: 82d6c268-7337-45af-aa2d-2d509cd46bef
            filterBySpanID: false
            filterByTraceID: false
            query: '{env=~".+"}  |= "$${__trace.traceId}" |= "$${__span.spanId}"'
            spanEndTimeShift: "+1m"
            spanStartTimeShift: "-1m"
            tags: []
          nodeGraph:
            enabled: true
          search:
            hide: false
          lokiSearch:
            datasourceUid: 82d6c268-7337-45af-aa2d-2d509cd46bef
          serviceMap:
            datasourceUid: e4e0224e-c538-4ae6-9468-dbcdb40209c0
          #      spanBar:
          #        type: Duration
          spanBar:
            type: "Tag"
            tag: "http.path"
      - name: Loki
        type: loki
        access: proxy
        orgId: 1
        url: http://loki-svc.monitoring.svc.cluster.local:3100
        basicAuth: false
        isDefault: false
        version: 1
        editable: true
        apiVersion: 1
        database: ""
        jsonData:
          derivedFields:
            - datasourceUid: 337b05fb-0159-4229-b9ce-ca151182522f
              matcherRegex: ".+\\[(.+?),.+\\].+"
              name: traceId
              url: "$${__value.raw}"
        uid: 82d6c268-7337-45af-aa2d-2d509cd46bef