apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: grafana
          image: grafana/grafana:9.5.3
          imagePullPolicy: Always
          env:
            # Minio access key and secret key
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: "Admin"
            - name: GF_AUTH_DISABLE_LOGIN_FORM
              value: "true"
            - name: GF_FEATURE_TOGGLES_ENABLE
              value: "tempoSearch traceqlEditor traceToMetrics"
          ports:
            - containerPort: 3000
              name: http-grafana
              protocol: TCP
          volumeMounts:
            - name: grafana-pv
              mountPath: /var/lib/grafana
            - name: datasources-config
              mountPath: /etc/grafana/provisioning/datasources
            - name: dashboards-config
              mountPath: /etc/grafana/provisioning/dashboards
      volumes:
        - name: grafana-pv
          persistentVolumeClaim:
            claimName: grafana-pvc
        - name: datasources-config
          configMap:
            name: grafana-datasources
            items:
              - key: datasources.yml
                path: datasources.yml
        - name: dashboards-config
          configMap:
            name: grafana-dashboards
            items:
              - key: default.yaml
                path: default.yaml
              - key: apm.json
                path: apm.json
              - key: application.json
                path: application.json
              - key: micrometer.json
                path: micrometer.json