apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
  namespace: monitoring
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    output {
      stdout { codec => rubydebug }
      loki { 
        url => "http://loki-service:3100/loki/api/v1/push"
        message_field => "message"
      }
    }