apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Tempo
    orgId: 1
#  - name: Jaeger
#    orgId: 1
  - name: Elasticsearch
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    uid: e4e0224e-c538-4ae6-9468-dbcdb40209c0
  #  - name: Jaeger
#    type: jaeger
#    access: proxy
#    orgId: 1
#    url: http://jaeger:16686
#    basicAuth: false
#    isDefault: false
#    version: 1
#    editable: true
#    apiVersion: 1
#    uid: c536e3ff-1f5f-481b-82ea-614f4aaefb80
  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
    apiVersion: 1
    uid: 337b05fb-0159-4229-b9ce-ca151182522f
    jsonData:
      httpMethod: GET
      nodeGraph:
        enabled: true
      serviceMap:
        datasourceUid: e4e0224e-c538-4ae6-9468-dbcdb40209c0
      spanBar:
        type: Duration
      traceQuery:
        timeShiftEnabled: false
      tracesToLogsV2:
        datasourceUid: cf73c39a-eb50-4a43-b0ce-1b6e9abc5c93
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    orgId: 1
    url: http://elasticsearch:9200
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    apiVersion: 1
    database: "cqrs-logstash-index"
    uid: cf73c39a-eb50-4a43-b0ce-1b6e9abc5c93
    jsonData:
      includeFrozen: false
      logLevelField: "Severity"
      logMessageField: "message"
      maxConcurrentShardRequests: 5
      timeField: "@timestamp"
