apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Jaeger
    orgId: 1
  - name: Elasticsearch
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
    uid: 4a365154-273c-4eff-a9b6-43172c42e52b
  - name: Jaeger
    type: jaeger
    access: proxy
    orgId: 1
    url: http://jaeger:16686
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    apiVersion: 1
    uid: c536e3ff-1f5f-481b-82ea-614f4aaefb80
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    orgId: 1
    url: http://elasticsearch:9200
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    apiVersion: 1
    database: "cqrs-logstash-index"
    uid: dc494c69-8553-4a2f-8f8d-5103fb291109
    jsonData:
      includeFrozen: false
      logLevelField: "Severity"
      logMessageField: "message"
      maxConcurrentShardRequests: 5
      timeField: "@timestamp"
