kind: Service
apiVersion: v1
metadata:
  name: prometheus-svc
spec:
  selector:
    app: prometheus
  ports:
    - name: prometheus-ui
      nodePort: 30900
      protocol: TCP
      port: 9090
      targetPort: 9090
  type: NodePort