apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-store
  template:
    metadata:
      labels:
        app: event-store
    spec:
      containers:
        - name: event-store
          image: quarkus-cqrs/event-store:1.0.0-SNAPSHOT
          ports:
            - containerPort: 9020
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: BROKER://kafka-svc.cqrs.svc.cluster.local:9093
            - name: QUARKUS_HTTP_PORT
              value: "9020"
            - name: QUARKUS_HTTP_SSL_PORT
              value: "9021"
            - name: QUARKUS_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: postgres-config
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: postgres-secret
            - name: QUARKUS_DATASOURCE_DB_KIND
              value: postgresql
            - name: QUARKUS_DATASOURCE_REACTIVE_URL
              value: vertx-reactive:postgresql://postgres:5432/microservices
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: jdbc:postgresql://postgres:5432/microservices

---
apiVersion: v1
kind: Service
metadata:
  name: event-store
spec:
  type: NodePort
  ports:
    - port: 9020
      protocol: TCP
      targetPort: 9020
      name: http
  selector:
    app: event-store