apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
  labels:
    app: mongo
data:
  database: "microservices"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  labels:
    app: mongo
data:
  password: "cGFzc3dvcmQxMjM="
  username: "YWRtaW51c2Vy"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-data
  labels:
    type: local
    app: mongo
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/mongo"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-claim
  labels:
    app: mongo
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  strategy: {}
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - image: docker.io/bitnami/mongodb:7.0
          name: mongo
#          args: ["--dbpath","/data/db"]
          env:
            - name: MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: database
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
          volumeMounts:
            - name: "mongo-data-dir"
              mountPath: "/data/db"
      volumes:
        - name: "mongo-data-dir"
          persistentVolumeClaim:
            claimName: "mongodb-claim"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo
spec:
  type: NodePort
  ports:
    - port: 27017
  selector:
    app: mongo