apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: view-store
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: view-store
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50