apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-configmap
  namespace: monitoring
  labels:
    k8s-app: tempo
data:
  tempo.yml: |-
    server:
      http_listen_port: 3200
    
    distributor:
      log_received_traces: true
      receivers:
        otlp:
          protocols:
            grpc:
    
    metrics_generator:
      processor:
        span_metrics:
          dimensions:
            - http.method
            #        - http.target
            #        - http.status_code
            - service.version
        service_graphs:
          dimensions:
            - http.method
            #        - http.target
            #        - http.status_code
            - service.version
      registry:
        collection_interval: 5s
        external_labels:
          source: tempo
      storage:
        path: /tmp/tempo/generator/wal
        remote_write:
          - url: http://prometheus-service:9090/api/v1/write
            send_exemplars: true
    
    storage:
      trace:
        backend: local
        wal:
          path: /tmp/tempo/wal
        local:
          path: /tmp/tempo/blocks
    
    overrides:
      metrics_generator_processors: [service-graphs, span-metrics] # enables metrics generator