apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo-deployment
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo
          image: grafana/tempo:2.1.1
          args:
            - -config.file=/etc/tempo/tempo.yml
          ports:
            - containerPort: 3200
            - containerPort: 4317
          volumeMounts:
            - name: config-volume
              mountPath: /etc/tempo
      volumes:
        - name: config-volume
          configMap:
            name: tempo-configmap
            items:
              - key: tempo.yml
                path: tempo.yml